In [1]:
import torch
import numpy as np

print("--- 1. Tensor(sizes) / torch.empty(sizes) ---")
# Tensor(sizes) 是 torch.empty(sizes) 的别名，用于创建一个指定形状但未初始化的张量。
# 它的值是内存中当前存在的任意值。
# 注意：PyTorch 默认创建的 Tensor 是 float32 类型 [4]。
t_empty = torch.empty(2, 3)
print(f"torch.empty(2, 3):\n{t_empty}\n") # cite: 1, 4

print("--- 2. tensor(data) ---")
# 从 Python 列表、元组或 NumPy 数组创建张量，类似于 NumPy 的 np.array [1, 5, 11]。
# 数据类型会自动推断 [11]。
data = [[1, 2], [3, 4]]
t_from_list = torch.tensor(data)
print(f"torch.tensor([[1, 2], [3, 4]]):\n{t_from_list}\n") # cite: 1, 11

numpy_array = np.array([5, 6, 7])
t_from_numpy = torch.tensor(numpy_array) # 或者 torch.from_numpy(numpy_array) [1]
print(f"torch.tensor(np.array([5, 6, 7])):\n{t_from_numpy}\n") # cite: 1

print("--- 3. ones(sizes) ---")
# 创建一个指定形状的张量，所有元素都为 1 [1, 9, 30]。
t_ones = torch.ones(2, 3)
print(f"torch.ones(2, 3):\n{t_ones}\n") # cite: 1, 9

print("--- 4. zeros(sizes) ---")
# 创建一个指定形状的张量，所有元素都为 0 [1, 6, 8]。
t_zeros = torch.zeros(3, 2)
print(f"torch.zeros(3, 2):\n{t_zeros}\n") # cite: 1, 6

print("--- 5. eye(sizes) ---")
# 创建一个 2D 张量（单位矩阵），对角线为 1，其余为 0 [25, 27]。
# 参数 n 为行数，m 为列数。如果只提供 n，则创建一个 n x n 的方阵 [26]。
t_eye_square = torch.eye(3)
print(f"torch.eye(3):\n{t_eye_square}\n") # cite: 25

t_eye_rect = torch.eye(4, 2)
print(f"torch.eye(4, 2):\n{t_eye_rect}\n") # cite: 26

print("--- 6. arange(s, e, step) ---")
# 创建一个 1D 张量，包含从 s (start) 到 e (end) 的值，步长为 step (不包含 e) [2, 3]。
# 注意：torch.range() 已被弃用，应使用 torch.arange() [2]。
t_arange = torch.arange(0, 10, 2)
print(f"torch.arange(0, 10, 2):\n{t_arange}\n") # cite: 2

print("--- 7. linspace(s, e, steps) ---")
# 创建一个 1D 张量，包含从 s (start) 到 e (end) 之间均匀分布的 steps 个点 (包含 s 和 e) [2, 16, 29]。
t_linspace = torch.linspace(0, 1, 5)
print(f"torch.linspace(0, 1, 5):\n{t_linspace}\n") # cite: 16

print("--- 8. rand/randn(sizes) ---")
# rand(sizes): 创建一个指定形状的张量，元素是来自 [0, 1) 区间均匀分布的随机数 [1, 22]。
t_rand = torch.rand(2, 2)
print(f"torch.rand(2, 2):\n{t_rand}\n") # cite: 1

# randn(sizes): 创建一个指定形状的张量，元素是来自标准正态分布 (均值 0，方差 1) 的随机数 [14, 17, 24]。
t_randn = torch.randn(2, 2)
print(f"torch.randn(2, 2):\n{t_randn}\n") # cite: 14

print("--- 9. normal(mean, std) ---")
# 创建一个张量，其中的随机数来自单独的正态分布，其均值和标准差由 mean 和 std 参数指定 [7, 10, 12]。
# mean 和 std 可以是标量或形状匹配的张量。
mean_tensor = torch.tensor([0.0, 1.0])
std_tensor = torch.tensor([1.0, 0.5])
t_normal = torch.normal(mean=mean_tensor, std=std_tensor)
print(f"torch.normal(mean=torch.tensor([0.0, 1.0]), std=torch.tensor([1.0, 0.5])):\n{t_normal}\n") # cite: 10

# 也可以用标量均值和标准差
t_normal_scalar = torch.normal(mean=0.0, std=1.0, size=(2, 2))
print(f"torch.normal(mean=0.0, std=1.0, size=(2, 2)):\n{t_normal_scalar}\n") # cite: 10

print("--- 10. randperm(m) ---")
# 生成一个从 0 到 n-1 (不包含 n) 的整数随机排列的 1D 张量 [19, 23, 36]。
# 常用语洗牌数据集或生成随机序列 [19, 36]。
t_randperm = torch.randperm(5)
print(f"torch.randperm(5):\n{t_randperm}\n") # cite: 19

--- 1. Tensor(sizes) / torch.empty(sizes) ---
torch.empty(2, 3):
tensor([[4.2973e+09, 8.8702e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

--- 2. tensor(data) ---
torch.tensor([[1, 2], [3, 4]]):
tensor([[1, 2],
        [3, 4]])

torch.tensor(np.array([5, 6, 7])):
tensor([5, 6, 7], dtype=torch.int32)

--- 3. ones(sizes) ---
torch.ones(2, 3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])

--- 4. zeros(sizes) ---
torch.zeros(3, 2):
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

--- 5. eye(sizes) ---
torch.eye(3):
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

torch.eye(4, 2):
tensor([[1., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.]])

--- 6. arange(s, e, step) ---
torch.arange(0, 10, 2):
tensor([0, 2, 4, 6, 8])

--- 7. linspace(s, e, steps) ---
torch.linspace(0, 1, 5):
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

--- 8. rand/randn(sizes) ---
torch.rand(2, 2):
tensor([[0.6339, 0.9639],
        [0.2309, 0.9678]])

torch.ran

In [6]:
import torch

print("--- 1. 加法操作 (Addition) ---")
# 逐元素加法 [1]。
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

# 方法一：使用运算符 '+' [1]
c_add_op = a + b
print(f"a + b:\n{c_add_op}\n")

# 方法二：使用 torch.add() 函数 [1]
c_add_func = torch.add(a, b)
print(f"torch.add(a, b):\n{c_add_func}\n")

# 方法三：in-place 加法 (就地操作)，会修改原 Tensor [1]
# 注意：PyTorch 中的就地操作通常以 '_' 结尾 [1, 2]。
a.add_(b)
print(f"a.add_(b) (修改后的 a):\n{a}\n")

print("--- 2. 索引 (Indexing) ---")
# PyTorch 的索引与 NumPy 类似 [1]。
tensor = torch.tensor([[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]])

# 获取单个元素
print(f"tensor[0, 0]: {tensor[0, 0]}\n") # 获取第一行第一列的元素 [1]

# 获取一行
print(f"tensor[1, :]: {tensor[1, :]}\n") # 获取第二行所有元素 [1]
print(f"tensor[1]: {tensor[1]}\n")      # 简写形式 [1]

# 获取一列
print(f"tensor[:, 2]: {tensor[:, 2]}\n") # 获取第三列所有元素 [1]

# 获取子区域
print(f"tensor[0:2, 0:2]:\n{tensor[0:2, 0:2]}\n") # 获取左上角 2x2 子矩阵 [1]

# 使用列表或张量进行高级索引 (Fancy Indexing)
indices_rows = torch.tensor([0, 2])
indices_cols = torch.tensor([0, 1])
print(f"tensor[indices_rows, indices_cols]: {tensor[indices_rows, indices_cols]}\n") # 获取 (0,0) 和 (2,1) 处的元素 [1]

print("--- 3. 维度变换 (Reshaping / View) ---")
# .view() 或 .reshape() 用于改变 Tensor 的形状 [1, 3]。
# .view() 共享底层数据，而 .reshape() 可能复制数据 [1]。

x = torch.randn(4, 4)
print(f"原始张量 x (4x4):\n{x}\n")

# .view() 改变形状，共享数据 [1, 3]。
y = x.view(16) # 将 4x4 变为 1x16 [1]
print(f"x.view(16):\n{y}\n")

z = x.view(-1, 8) # -1 会自动推断维度大小 [1, 3]。这里是 2x8
print(f"x.view(-1, 8):\n{z}\n")

# .reshape() 也是改变形状，如果内存不连续可能会复制数据 [1]。
a_reshape = x.reshape(2, 8)
print(f"x.reshape(2, 8):\n{a_reshape}\n")

print("--- 4. 拼接 (Concatenation) ---")
# torch.cat() 用于在给定维度上拼接多个张量 [1]。
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

# 沿维度 0 拼接 (按行堆叠) [1]
cat_dim0 = torch.cat((tensor1, tensor2), dim=0)
print(f"torch.cat((tensor1, tensor2), dim=0):\n{cat_dim0}\n")

# 沿维度 1 拼接 (按列堆叠) [1]
cat_dim1 = torch.cat((tensor1, tensor2), dim=1)
print(f"torch.cat((tensor1, tensor2), dim=1):\n{cat_dim1}\n")

print("--- 5. 堆叠 (Stacking) ---")
# torch.stack() 用于沿着一个新的维度堆叠多个张量 [1, 13]。
# 类似于将多个同形状的张量“垒起来” [13]。
stack_dim0 = torch.stack((tensor1, tensor2), dim=0)
print(f"torch.stack((tensor1, tensor2), dim=0):\n{stack_dim0}\n")
# 结果形状是 (2, 2, 2)

stack_dim1 = torch.stack((tensor1, tensor2), dim=1)
print(f"torch.stack((tensor1, tensor2), dim=1):\n{stack_dim1}\n")
# 结果形状是 (2, 2, 2)

print("--- 6. 展开 (Squeeze) 和 扩充 (Unsqueeze) ---")
# squeeze() 移除所有大小为 1 的维度 [1, 28]。
# unsqueeze() 在指定维度添加一个大小为 1 的维度 [1, 21]。

x_squeeze = torch.zeros(1, 2, 1, 3)
print(f"原始张量 x_squeeze (1x2x1x3):\n{x_squeeze.shape}\n")

y_squeezed = x_squeeze.squeeze() # 移除所有大小为 1 的维度
print(f"x_squeeze.squeeze(): {y_squeezed.shape}\n") # 形状变为 (2, 3) [1, 28]

z_squeezed_dim = x_squeeze.squeeze(0) # 只移除指定维度 (dim=0) 的大小为 1 的维度 [1]
print(f"x_squeeze.squeeze(0): {z_squeezed_dim.shape}\n") # 形状变为 (2, 1, 3)

a_unsqueeze = torch.tensor([1, 2, 3]) # 形状是 (3,)
print(f"原始张量 a_unsqueeze (形状 (3,)):\n{a_unsqueeze.shape}\n")

b_unsqueezed = a_unsqueeze.unsqueeze(0) # 在 dim=0 处添加一个维度
print(f"a_unsqueeze.unsqueeze(0): {b_unsqueezed.shape}\n") # 形状变为 (1, 3) [1, 21]

c_unsqueezed = a_unsqueeze.unsqueeze(1) # 在 dim=1 处添加一个维度
print(f"a_unsqueeze.unsqueeze(1): {c_unsqueezed.shape}\n") # 形状变为 (3, 1) [1, 21]

print("--- 7. 转置 (Transpose) ---")
# .T 属性或 .transpose() 方法用于交换两个维度 [1]。
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
print(f"原始矩阵 (2x3):\n{matrix.view}\n")

matrix_t = matrix.T # .T 属性是 .transpose(0, 1) 的简写 [1]
print(f"矩阵转置 (.T):\n{matrix_t}\n") # 形状变为 3x2

# 对于更高维度的张量，可以使用 transpose(dim0, dim1)
high_dim_tensor = torch.randn(2, 3, 4)
print(f"原始高维张量 (2x3x4):\n{high_dim_tensor.shape}\n")
transposed_tensor = high_dim_tensor.transpose(0, 2) # 交换维度 0 和维度 2 [1]
print(f"高维张量转置 (交换 dim 0 和 dim 2): {transposed_tensor.shape}\n") # 形状变为 4x3x2

print("--- 8. 元素数量 (Number of elements) ---")
# .numel() 返回张量中元素的总数量 [1].
# .size() 或 .shape 返回张量的形状 [1].
elements_count = tensor.numel()
print(f"张量 tensor 的元素数量: {elements_count}\n") # cite: 1

print("--- 9. 类型转换 (Type Casting) ---")
# 使用 .to() 或 .type() 方法转换数据类型 [1].
float_tensor = torch.ones(2, 2, dtype=torch.float32)
print(f"原始浮点张量 (dtype: {float_tensor.dtype}):\n{float_tensor}\n")

int_tensor = float_tensor.to(torch.int64) # 转换为 long (int64) 类型 [1]
print(f"转换为 int64 的张量 (dtype: {int_tensor.dtype}):\n{int_tensor}\n")

double_tensor = float_tensor.type(torch.float64) # 另一种类型转换方式 [1]
print(f"转换为 float64 的张量 (dtype: {double_tensor.dtype}):\n{double_tensor}\n")

print("--- 10. 克隆 (Clone) ---")
# .clone() 创建张量的一个副本 [1].
original_tensor = torch.tensor([1, 2, 3])
cloned_tensor = original_tensor.clone()
cloned_tensor[0] = 99
print(f"原始张量 (修改克隆后): {original_tensor}\n")
print(f"克隆张量 (被修改): {cloned_tensor}\n")

print("--- 11. item() ---")
# 对于只包含一个元素的张量，可以使用 .item() 方法获取其 Python 数值 [1].
single_element_tensor = torch.tensor(42)
python_number = single_element_tensor.item()
print(f"单元素张量: {single_element_tensor}, Python 数值: {python_number}\n") # cite: 1
# 如果张量包含多个元素，使用 .item() 会报错。

--- 1. 加法操作 (Addition) ---
a + b:
tensor([[ 6,  8],
        [10, 12]])

torch.add(a, b):
tensor([[ 6,  8],
        [10, 12]])

a.add_(b) (修改后的 a):
tensor([[ 6,  8],
        [10, 12]])

--- 2. 索引 (Indexing) ---
tensor[0, 0]: 10

tensor[1, :]: tensor([13, 14, 15])

tensor[1]: tensor([13, 14, 15])

tensor[:, 2]: tensor([12, 15, 18])

tensor[0:2, 0:2]:
tensor([[10, 11],
        [13, 14]])

tensor[indices_rows, indices_cols]: tensor([10, 17])

--- 3. 维度变换 (Reshaping / View) ---
原始张量 x (4x4):
tensor([[ 0.7731,  0.7889, -0.3229,  2.1550],
        [-0.9092, -1.4473, -0.8163, -0.2732],
        [ 2.1582,  1.0211, -2.0695, -2.7672],
        [ 1.2168, -1.3652, -1.2796,  1.1501]])

x.view(16):
tensor([ 0.7731,  0.7889, -0.3229,  2.1550, -0.9092, -1.4473, -0.8163, -0.2732,
         2.1582,  1.0211, -2.0695, -2.7672,  1.2168, -1.3652, -1.2796,  1.1501])

x.view(-1, 8):
tensor([[ 0.7731,  0.7889, -0.3229,  2.1550, -0.9092, -1.4473, -0.8163, -0.2732],
        [ 2.1582,  1.0211, -2.0695, -2.7672,  1.216